routes/web.php
<?php

use App\Http\Controllers\ClientController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('/clients', ClientController::class);

app/Models/Client.php
<?php

namespace App\Models;

use App\Models\User;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Client extends Model
{

    use HasFactory;
    use SoftDeletes;

    protected $table = "clients";

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Models\Client;
use Illuminate\Support\Str;
use Exception;

class ClientController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $sortBy = $request->get('sortby', 'dni_asc');
        $search = $request->get('search');

        [$sortField, $sortOrder] = $this->getSortFields($sortBy);

        $query = Client::orderBy($sortField, $sortOrder);

        if (!is_null($search)) {
            $query->where('dni', 'like', "%{$search}%");
        }

        $clients = $query->get();

        return view('clients.index', compact('clients', 'sortBy'));
    }

    protected function getSortFields($sortBy)
    {
        $sortOrder = Str::endsWith($sortBy, 'desc') ? 'desc' : 'asc';
        $sortField = Str::startsWith($sortBy, 'last_name') ? 'last_name' : 'dni';

        return [$sortField, $sortOrder];
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('clients.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {

            $hasClientSavedForUser = Client::query()
                ->where('dni', $request->input('dni'))
                ->exists();

            if ($hasClientSavedForUser) {
                return redirect()->route('clients.index')->with('error', 'Ya existe un registro con el numero de cédula ingresado');
            }

            $request->validate([
                'dni' => 'required|unique:clients|max:255',
                'name' => 'required',
                'last_name' => 'required',
                'phone' => 'required',
                'address' => 'required',
            ]);

            $client = new Client;
            $client->dni = $request->dni;
            $client->name = $request->name;
            $client->last_name = $request->last_name;
            $client->phone = $request->phone;
            $client->address = $request->address;
            $client->user_id = Auth::id();

            $client->save();

            return redirect()->route('clients.index')->with('success', 'Cliente creado correctamente!');
        } catch (Exception $e) {

            return redirect()->route('clients.index')->with('error', 'Ocurrió un error al crear el cliente');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $client = Client::findOrFail($id);

            return view('clients.show', compact('client'));
        } catch (Exception $e) {

            return redirect()->route('clients.index')->with('error', 'Ocurrió un error al buscar el cliente');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $request->validate([
                'dni' => 'required|max:255|unique:clients,dni,' . $id,
                'name' => 'required',
                'last_name' => 'required',
                'phone' => 'required',
                'address' => 'required',
            ]);

            $client = Client::findOrFail($id);

            $client->dni = $request->dni;
            $client->name = $request->name;
            $client->last_name = $request->last_name;
            $client->phone = $request->phone;
            $client->address = $request->address;

            $client->save();

            return redirect()->route('clients.index')->with('success', 'Cliente actualizado correctamente!');
        } catch (Exception $e) {

            dd($e);
            return redirect()->route('clients.index')
                ->with('error', 'Ocurrió un error al actualizar el cliente');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $client = Client::findOrFail($id);
            $client->delete();

            return redirect()->route('clients.index')
                ->with('success', 'Cliente eliminado correctamente!');
        } catch (Exception $e) {
            return redirect()->route('clients.index')
                ->with('error', 'Ocurrió un error al eliminar el cliente');
        }
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/clients/create.blade.php
@extends('layouts.app') @section('content')
<div class="container">
    <h2>Crear Cliente</h2>

    @if (Session::has('success'))
    <div class="alert alert-danger">
        {{ Session::get("error") }}
    </div>
    @endif

    <form action="{{ route('clients.store') }}" method="POST">
        @csrf
        <div class="form-group">
            <label for="dni">Cédula</label>
            <input
                type="number"
                min="1000000"
                id="dni"
                name="dni"
                class="form-control"
                required
            />
        </div>

        <div class="form-group">
            <label for="name">Nombres</label>
            <input
                type="text"
                id="name"
                name="name"
                class="form-control"
                required
            />
        </div>

        <div class="form-group">
            <label for="last_name">Apellidos</label>
            <input
                type="text"
                id="last_name"
                name="last_name"
                class="form-control"
                required
            />
        </div>

        <div class="form-group">
            <label for="phone">Teléfono</label>
            <input
                type="text"
                minlength="9"
                id="phone"
                name="phone"
                class="form-control"
                required
            />
        </div>

        <div class="form-group">
            <label for="address">Dirección</label>
            <textarea
                id="address"
                name="address"
                class="form-control"
                required
            ></textarea>
        </div>

        <br />
        <button type="submit" class="btn btn-primary">Crear Cliente</button>
    </form>
</div>

@endsection

resources/views/clients/index.blade.php
@extends('layouts.app') @section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div
                    class="card-header d-flex justify-content-between align-items-center"
                >
                    {{ __("Clientes") }}
                    <a
                        class="btn btn-success"
                        href="{{ route('clients.create') }}"
                    >
                        Crear cliente
                    </a>
                </div>

                @if (session('error'))
                <div class="alert alert-danger">
                    {{ session("error") }}
                </div>
                @endif @if (session('success'))
                <div class="alert alert-success">
                    {{ session("success") }}
                </div>
                @endif

                <br />
                <div class="container">
                    <form action="{{ route('clients.index') }}" method="GET">
                        <div class="input-group mb-3">
                            <input
                                class="input-group-text"
                                type="text"
                                name="search"
                                placeholder="Buscar por cedula"
                                value="{{ old('search', request()->search) }}"
                                autocomplete="off"
                            />
                            <button class="btn btn-info" type="submit">
                                Buscar
                            </button>
                        </div>
                    </form>

                    <table class="table">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col">Id</th>
                                <th>
                                    <a
                                        href="{{ route('clients.index', ['sortby' => $sortBy === 'dni_asc' ? 'dni_desc' : 'dni_asc']) }}"
                                    >
                                        Cedula @if (Str::startsWith($sortBy,
                                        'dni')) @if ($sortBy === 'dni_asc')
                                        &uarr; @else &darr; @endif @endif
                                    </a>
                                </th>
                                <th scope="col">Nombres</th>
                                <th scope="col">
                                    <a
                                        href="{{ route('clients.index', ['sortby' => $sortBy === 'last_name_asc' ? 'last_name_desc' : 'last_name_asc']) }}"
                                    >
                                        Apellidos @if (Str::startsWith($sortBy,
                                        'last_name')) @if ($sortBy ===
                                        'last_name_asc') &uarr; @else &darr;
                                        @endif @endif
                                    </a>
                                </th>
                                <th scope="col">Teléfono</th>
                                <th scope="col">Dirección</th>
                                <th scope="col">Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($clients as $client)
                            <tr>
                                <td>{{ $client->id }}</td>
                                <td>{{ $client->dni }}</td>
                                <td>{{ $client->name }}</td>
                                <td>{{ $client->last_name }}</td>
                                <td>{{ $client->phone }}</td>
                                <td>{{ $client->address }}</td>

                                <td class="d-flex">
                                    <div>
                                        <a
                                            href="{{ route('clients.edit', $client->id) }}"
                                            class="btn btn-primary"
                                            >Editar</a
                                        >
                                    </div>

                                    <form
                                        action="{{ route('clients.destroy', $client->id) }}"
                                        method="POST"
                                    >
                                        @csrf @method('DELETE')
                                        <button
                                            type="submit"
                                            class="btn btn-danger"
                                        >
                                            Eliminar
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td colspan="6">
                                    No hay clientes registrados.
                                </td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    @endsection
</div>

resources/views/clients/show.blade.php
@extends('layouts.app') @section('content')
<div class="container">
    <h2>Editar Cliente</h2>

    <form action="{{ route('clients.update', $client->id) }}" method="POST">
        @csrf @method('PUT')
        <div class="form-group">
            <label for="dni">Cédula</label>
            <input
                type="number"
                min="1000000"
                id="dni"
                name="dni"
                class="form-control"
                value="{{ old('dni', $client->dni) }}"
                required
            />
        </div>

        <div class="form-group">
            <label for="name">Nombres</label>
            <input
                type="text"
                id="name"
                name="name"
                class="form-control"
                value="{{ old('name', $client->name) }}"
                required
            />
        </div>

        <div class="form-group">
            <label for="last_name">Apellidos</label>
            <input
                type="text"
                id="last_name"
                name="last_name"
                class="form-control"
                value="{{ old('last_name', $client->last_name) }}"
                required
            />
        </div>

        <div class="form-group">
            <label for="phone">Teléfono</label>
            <input
                type="text"
                minlength="9"
                id="phone"
                name="phone"
                class="form-control"
                value="{{ old('phone', $client->phone) }}"
                required
            />
        </div>

        <div class="form-group">
            <label for="address">Dirección</label>
            <textarea
                id="address"
                name="address"
                class="form-control"
                required
                >{{ old('address', $client->address) }}</textarea
            >
        </div>

        <br />
        <button type="submit" class="btn btn-primary">
            Actualizar Cliente
        </button>
    </form>
</div>

@endsection

resources/views/home.blade.php
@extends('layouts.app') @section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __("Dashboard") }}</div>

                <div class="card-body">
                    @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session("status") }}
                    </div>
                    @endif

                    <br />
                    <a
                        class="btn btn-primary"
                        href="{{ route('clients.index') }}"
                        >Ir a clientes</a
                    >
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}" />

        <title>{{ config("app.name", "Laravel Clients") }}</title>

        <!-- Fonts -->
        <link rel="dns-prefetch" href="//fonts.bunny.net" />
        <link
            href="https://fonts.bunny.net/css?family=Nunito"
            rel="stylesheet"
        />

        <!-- Scripts -->
        @vite(['resources/sass/app.scss', 'resources/js/app.js'])
    </head>
    <body>
        <div id="app">
            <nav
                class="navbar navbar-expand-md navbar-light bg-white shadow-sm"
            >
                <div class="container">
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config("app.name", "Laravel Clients") }}
                    </a>
                    <button
                        class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="{{ __('Toggle navigation') }}"
                    >
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div
                        class="collapse navbar-collapse"
                        id="navbarSupportedContent"
                    >
                        <!-- Left Side Of Navbar -->
                        <ul class="navbar-nav me-auto">
                            <a
                                class="nav-link"
                                href="{{ route('clients.index') }}"
                                >{{ __("Clientes") }}</a
                            >
                        </ul>

                        <!-- Right Side Of Navbar -->
                        <ul class="navbar-nav ms-auto">
                            <!-- Authentication Links -->
                            @guest @if (Route::has('login'))
                            <li class="nav-item">
                                <a
                                    class="nav-link"
                                    href="{{ route('login') }}"
                                    >{{ __("Login") }}</a
                                >
                            </li>
                            @endif @if (Route::has('register'))
                            <li class="nav-item">
                                <a
                                    class="nav-link"
                                    href="{{ route('register') }}"
                                    >{{ __("Register") }}</a
                                >
                            </li>
                            @endif @else
                            <li class="nav-item dropdown">
                                <a
                                    id="navbarDropdown"
                                    class="nav-link dropdown-toggle"
                                    href="#"
                                    role="button"
                                    data-bs-toggle="dropdown"
                                    aria-haspopup="true"
                                    aria-expanded="false"
                                    v-pre
                                >
                                    {{ Auth::user()->name }}
                                </a>

                                <div
                                    class="dropdown-menu dropdown-menu-end"
                                    aria-labelledby="navbarDropdown"
                                >
                                    <a
                                        class="dropdown-item"
                                        href="{{ route('logout') }}"
                                        onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();"
                                    >
                                        {{ __("Logout") }}
                                    </a>

                                    <form
                                        id="logout-form"
                                        action="{{ route('logout') }}"
                                        method="POST"
                                        class="d-none"
                                    >
                                        @csrf
                                    </form>
                                </div>
                            </li>
                            @endguest
                        </ul>
                    </div>
                </div>
            </nav>

            <main class="py-4">@yield('content')</main>
        </div>
    </body>
</html>